image: node:10

cache:
  paths:
  - node_modules/

stages:
  - test

show-tests:
  stage: test
  script:
   - npm install
   - npm run show-tests
  artifacts:
    paths:
    - results.csv
    expire_in: 1 week

launch-tests:
  stage: test
  script:
   - npm install
   - npm run launch-tests
  artifacts:
    paths:
    - results.csv
    expire_in: 1 week